### ISSUE TITLE
基于Dubbo的Mock测试工具只需要在消费端配置，不用在提供端配置吗？

### ISSUE THREAD

**Issue by JKAK47** [threeq/dubbo-mock#2]

**Comment by threeq** [comment]
不用。
在单元测试中调用 dubbo 服务的时候，请求会被 `MockProxy` 过滤器拦截，这个地方会直接返回我们设置好的 mock 对象，不会向 dubbo 服务器提供者发起网络请求，一般情况是不需要启动 dubbo 服务端。

这样做的目的主要是为了在编写上层业务单元测试的时候，不要依赖网络服务。让我们的单元测试跑得更快

**Comment by JKAK47** [comment]
按照 dubbo官方文档提供的[本地伪装](http://dubbo.io/user-guide/demos/%E6%9C%AC%E5%9C%B0%E4%BC%AA%E8%A3%85.html)，在服务端没启动时候不会调用我们设置好的mock对象中定义好的方法

**Comment by threeq** [comment]
这个和官方的那个不一样的。
我们的目的都有很大却别：我这个只能用于开发中编写的单元测试当中；官网的那个主要目的是提供服务的降级和容错功能。
所以我这里的实现和官网的 "本地伪装" 完全是 2 个东西
