### ISSUE TITLE
你好，你这个工程基于grandle构建，看的不是很懂。能不能讲解下。

### ISSUE THREAD

**Issue by JKAK47** [threeq/dubbo-mock#3]

**Comment by threeq** [comment]
能说具体问题吗 ？看不懂是指下面这样吗：
1. `dubbo-mock-core` dubbo-mock 核心实现
2. `dubbo-mock-demo` dubbo-mock 使用实例。demo 中提供了 `spock`、`mockito` 2 个例子
3. `docker-compose.yml` 开发时所依赖的组件服务: `zookeeper`
